# Provide a overwrite file with REVERSER_CUSTOM_CONFIG_PATH
app_name: "Reverser"
# How large should the generated thumbnails be
# This is a bounding box
thumbnail_size: 300
# The server which handles similar images search
  # Must respond like https://github.com/danbooru/iqdb
iqdb_server: "http://iqdb:5588"
# Matches either links or controller actions
log_ignore:
  - "ActiveStorage::DiskController#show"
  - "ActiveStorage::Blobs::RedirectController#show"
  - "/rails/active_storage"
  - "/sidekiq"

# These settings require a server restart
# Controls wether or not the logging should be intercepted
silence_log?: true
redis_url: "redis://redis"
