version: "3"

services:
  reverser:
    build: ./
    environment:
      DATABASE_URL: postgresql://reverser@postgres
      # Don't make bootsnap part of the tmpfs
      BOOTSNAP_CACHE_DIR: /
    volumes:
      - .:/app
      - build_assets:/app/public/build
      - active_storage:/app/public/storage
      - node_modules:/app/node_modules
      - yarn:/app/.yarn
      - bootsnap:/bootsnap
    tmpfs:
      - /app/tmp
    depends_on:
      - postgres
    ports:
      - 9000:9000

  postgres:
    image:  postgres:14-alpine
    environment:
      - POSTGRES_USER=reverser
      - POSTGRES_DB=reverser_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  iqdb:
    build:
      context: ./docker
      dockerfile: iqdb.Dockerfile

volumes:
  db_data:
  build_assets:
  active_storage:
  node_modules:
  yarn:
  bootsnap:
