version: "3"

x-environment: &common-env
  EXPOSED_VNC_PORT: ${EXPOSED_VNC_PORT:-7900}
  IQDB_URL: ${IQDB_URL:-http://iqdb:5588}
  SELENIUM_URL: ${SELENIUM_URL:-http://selenium:4444}

services:
  reverser:
    build:
      context: ./
      args:
        COMPOSE_PROFILES: ${COMPOSE_PROFILES-}
    image: reverser
    environment:
      <<: *common-env
      RAILS_SERVER_EXEC: bin/rails server -p ${EXPOSED_SERVER_PORT:-9000} -b 0.0.0.0 --pid /tmp/server.pid
      ESBUILD_EXEC: >-
        esbuild app/typescript/application.ts
        --target=chrome111,firefox111,safari16
        --bundle --sourcemap
        --outdir=public/build --loader:.png=file
        --entry-names=[name]-[hash] --metafile=public/build/manifest.json
        --watch=forever --color=true
      GOOD_JOB_EXEC: bundle exec good_job --queues=scraping:1;e6_iqdb:1;variant_generation:5;default:1;submission_download:5
    volumes:
      - .:/app
      - build_assets:/app/public/build
      - ${REVERSER_DATA_PATH:?}/active_storage:/app/public/storage
    depends_on:
      - postgres
      - iqdb
      - selenium
    ports:
      - "${BIND_IP:-127.0.0.1}:${EXPOSED_SERVER_PORT:-9000}:${EXPOSED_SERVER_PORT:-9000}"
    command: foreman start --color

  solargraph:
    image: reverser
    entrypoint: solargraph socket -h 0.0.0.0 -p 7659
    working_dir: $PWD
    volumes:
      - .:$PWD
    ports:
      - "7659:7659"
    profiles:
      - solargraph

  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=reverser
      - POSTGRES_DB=reverser_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${REVERSER_DATA_PATH:?}/db_data:/var/lib/postgresql/data
    shm_size: 256mb
    ports:
      - "${BIND_IP:-127.0.0.1}:${EXPOSED_POSTGRES_PORT:-34518}:5432"

  iqdb:
    image: ghcr.io/e621ng/iqdb:b988f000f17008677c7546c0c13623bc956b585d
    volumes:
      - ${REVERSER_DATA_PATH:?}/iqdb_data:/iqdb

  selenium:
    image: selenium/standalone-chrome:4.16.1-20231212
    environment:
      - SE_VNC_NO_PASSWORD=1
    shm_size: 2gb
    ports:
      - "${BIND_IP:-127.0.0.1}:${EXPOSED_VNC_PORT:-7900}:7900"

  # Profiles for standalone things

  rubocop:
    image: reverser
    volumes:
      - .:/app
      - rubocop_cache:/rubocop_cache
    entrypoint: bundle exec rubocop --cache-root /rubocop_cache
    profiles:
      - rubocop

  tests:
    image: reverser
    environment:
      <<: *common-env
      VIPS_WARNING: "0"
    volumes:
      - .:/app
    entrypoint: bundle exec rails test
    tmpfs:
      - /app/tmp/storage
    depends_on:
      - postgres
    profiles:
      - tests

networks:
  default:
    driver: bridge
    ipam:
      driver: default
    driver_opts:
      com.docker.network.bridge.name: br-reverser

volumes:
  build_assets:
  rubocop_cache:
