x-environment: &common-env
  EXPOSED_VNC_PORT: ${EXPOSED_VNC_PORT:-7900}
  IQDB_URL: ${IQDB_URL:-http://iqdb:5588}
  SELENIUM_URL: ${SELENIUM_URL:-http://selenium:4444}
  DEV_MODE: ${DEV_MODE:-false}

services:
  reverser:
    build:
      context: ./
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
    image: reverser
    user: ${DOCKER_USER:-root}
    environment:
      <<: *common-env
      RAILS_SERVER_EXEC: bin/rails server -p ${EXPOSED_SERVER_PORT:-9000} -b 0.0.0.0 --pid /tmp/server.pid
      ESBUILD_EXEC: >-
        esbuild app/typescript/application.ts
        --target=chrome111,firefox111,safari16
        --bundle --sourcemap
        --outdir=public/build --loader:.png=file
        --entry-names=[name]-[hash] --metafile=public/build/manifest.json
        --watch=forever --color=true
      GOOD_JOB_EXEC: bundle exec good_job --queues=scraping:1;e6_iqdb:1;variant_generation:5;default:1;submission_download:5
    volumes:
      - .:/app
      - ${REVERSER_DATA_PATH:-./data}/active_storage:/app/public/storage
    depends_on:
      postgres:
        condition: service_healthy
      iqdb:
        condition: service_started
      selenium:
        condition: service_started
    ports:
      - ${EXPOSED_SERVER_PORT:-9000}:${EXPOSED_SERVER_PORT:-9000}
    command: foreman start --color

  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=reverser
      - POSTGRES_DB=reverser_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${REVERSER_DATA_PATH:-./data}/db_data:/var/lib/postgresql/data
    shm_size: 256mb
    ports:
      - ${EXPOSED_POSTGRES_PORT:-34518}:5432
    healthcheck:
      test: [CMD-SHELL, pg_isready -d reverser_development -U reverser]
      interval: 10s
      timeout: 5s
      retries: 5

  iqdb:
    image: ghcr.io/e621ng/iqdb:d42a65ba35523eb46152744d68d8ff302c1c9f92
    volumes:
      - ${REVERSER_DATA_PATH:-./data}/iqdb_data:/iqdb

  selenium:
    image: selenium/standalone-chrome:4.22.0-20240621
    environment:
      - SE_VNC_NO_PASSWORD=1
    shm_size: 2gb
    ports:
      - ${EXPOSED_VNC_PORT:-7900}:7900

  # Profiles for standalone things

  rubocop:
    image: reverser
    volumes:
      - .:/app
    entrypoint: bundle exec rubocop
    profiles:
      - rubocop

  yamllint:
    build:
      dockerfile_inline: |
        FROM python:3.12-alpine3.20
        RUN pip install yamllint==1.35.1
        WORKDIR /app
    volumes:
      - .:/app
    entrypoint: yamllint -c .github/yamllint.yml -s .
    profiles:
      - yamllint

  csslint:
    build:
      dockerfile_inline: |
        FROM node:20-alpine3.20
        RUN npm install stylelint@16.6.1 stylelint-config-standard@36.0.1 -g
        WORKDIR /app
    volumes:
      - .:/app
    entrypoint: stylelint "**/*.css" --config .github/.stylelintrc.json
    profiles:
      - csslint

  tslint:
    build:
      dockerfile_inline: |
        FROM node:20-alpine3.20
        RUN npm install typescript@5.5.2 -g
        WORKDIR /app
    volumes:
      - .:/app
    entrypoint: tsc --noEmit -p .github/tsconfig.json
    profiles:
      - tslint

  tests:
    image: reverser
    user: ${DOCKER_USER:-root}
    environment:
      <<: *common-env
      VIPS_WARNING: "0"
    volumes:
      - .:/app
    entrypoint: bundle exec rails test
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tests
