version: "3"

services:
  reverser:
    build:
      context: ./
      args:
        COMPOSE_PROFILES: ${COMPOSE_PROFILES-}
    image: reverser
    volumes:
      - .:/app
      - build_assets:/app/public/build
      - ${REVERSER_DATA_PATH}/active_storage:/app/public/storage
      - temp:/app/tmp
    tmpfs:
      - /app/.pnpm-store
      - /app/node_modules
      - /app/tmp/cache
      - /app/tmp/pids
      - /app/tmp/sockets
    depends_on:
      - postgres
      - iqdb
      - selenium
    ports:
      - 9000:9000
    command: foreman start --color

  solargraph:
    image: reverser
    entrypoint: solargraph socket -h 0.0.0.0 -p 7659
    working_dir: $PWD
    volumes:
      - .:$PWD
    ports:
      - 7659:7659
    profiles:
      - solargraph

  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=reverser
      - POSTGRES_DB=reverser_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${REVERSER_DATA_PATH}/db_data:/var/lib/postgresql/data
    shm_size: 256mb
    ports:
      - 5432:5432

  iqdb:
    image: ghcr.io/earlopain/iqdb:de8f10e2ddd862c37dc39348d6cb1c30112be146
    volumes:
      - ${REVERSER_DATA_PATH}/iqdb_data:/iqdb

  selenium:
    image: selenium/standalone-chrome:4.8.0-20230210
    environment:
      - VNC_NO_PASSWORD=1
    shm_size: 2gb
    ports:
      - 7900:7900

  # Profiles for standalone things

  rubocop:
    image: reverser
    volumes:
      - .:/app
      - rubocop_cache:/rubocop_cache
    entrypoint: bundle exec rubocop --cache-root /rubocop_cache
    profiles:
      - rubocop

  tests:
    image: reverser
    volumes:
      - .:/app
    entrypoint: bundle exec rails test
    tmpfs:
      - /app/tmp/storage
    depends_on:
      - postgres
      - iqdb
      - selenium
    profiles:
      - tests

volumes:
  build_assets:
  rubocop_cache:
  temp:
