version: "3"

services:
  reverser:
    build: ./
    environment:
      DATABASE_URL: postgresql://reverser@postgres
      # Don't make bootsnap part of the tmpfs
      BOOTSNAP_CACHE_DIR: /
      REVERSER_CUSTOM_CONFIG_PATH: "/app/custom_config.yml"
    volumes:
      - .:/app
      - build_assets:/app/public/build
      - active_storage:/app/public/storage
      - node_modules:/app/node_modules
      - yarn:/app/.yarn
      - bootsnap:/bootsnap
      - temp:/app/tmp
    tmpfs:
      - /app/tmp/cache
      - /app/tmp/pids
      - /app/tmp/sockets
    depends_on:
      - postgres
      - redis
      - memcached
      - iqdb
      - selenium
    ports:
      - 9000:9000
    tty: true

  postgres:
    image:  postgres:14-alpine
    environment:
      - POSTGRES_USER=reverser
      - POSTGRES_DB=reverser_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:alpine

  iqdb:
    build: ./docker/iqdb
    volumes:
      - iqdb_data:/iqdb

  selenium:
    image: selenium/standalone-chrome:4.1.1-20220121
    shm_size: 2gb
    ports:
      - 7900:7900

volumes:
  db_data:
  redis_data:
  iqdb_data:
  build_assets:
  active_storage:
  node_modules:
  yarn:
  bootsnap:
  temp:
